blueprint:
  name: "Door Direction Trigger"
  description: >-
    Connects to a door sensor and a motion sensor, allowing setting actions
    for when the door is opened after the motion is tripped or not. This is
    especially useful for automatically triggering lights based on someone
    exiting or entering.


    The delay time between motion event and door opening is configurable.

  domain: automation
  source_url: https://github.com/gregmac/HomeAssistant-Blueprints/blob/main/door_direction_trigger.yaml

  input:
    door_entity:
      name: Door Sensor
      description: Door to trigger actions
      selector:
        entity: 
          domain: binary_sensor
          device_class: door

    motion_entity:
      name: Motion Sensor
      description: Motion sensor mounted near door, used to determine a person's direction
      selector:
        entity: 
          domain: binary_sensor
          device_class: motion

    timeout:
      name: Timeout
      description: >
        How long from when motion is detected before door must open for it to be considered
        as "motion before door".
      default: 10
      selector:
        number:
          min: 1
          max: 300
          unit_of_measurement: seconds

    cooldown:
      name: Cooldown
      description: >
        How long from when an action is run before another action can be triggered.
      default: 10
      selector:
        number:
          min: 1
          max: 300
          unit_of_measurement: seconds

    motion_first:
      name: Door opened after motion sensor
      description: Action to run when the door is opened after the motion sensor is triggered
      default: []
      selector:
        action: {}

    motion_after:
      name: Door opened before or without motion sensor
      description: Action to run when the door is opened before the motion sensor.
      default: []
      selector:
        action: {}

mode: single # important to not overlap triggers
max_exceeded: silent

variables:
  motion_entity: !input motion_entity
  door_entity: !input door_entity
  timeout: !input timeout
  cooldown: !input cooldown

trigger:
  - platform: state
    entity_id: !input motion_entity
    to: 'on'

  - platform: state
    entity_id: !input door_entity
    to: 'on'

action:
  - choose:
      - alias: Motion triggered
        conditions: "{{ trigger.entity_id == motion_entity }}"
        sequence:
          - wait_for_trigger:
              - platform: state
                entity_id: !input door_entity
                to: 'on'
            timeout: !input timeout
            continue_on_timeout: false # STOP all further execution on timeout (including not waiting for cooldown)

          - service: logbook.log
            data:
              name: "{{ this.attributes.friendly_name }}"
              message: "Door opened after motion triggered"
              entity_id: !input door_entity

          - if: { condition: template, value_template: "{{ true }}" }  # TODO - must be a better way?
            then: !input motion_first

      - alias: Door opened, no motion
        conditions: "{{ trigger.entity_id == door_entity }}"
        sequence:
          - service: logbook.log
            data:
              name: "{{ this.attributes.friendly_name }}"
              message: "Door opened before/without motion triggered"
              entity_id: !input door_entity

          - if: { condition: template, value_template: "{{ true }}" }  # TODO - must be a better way?
            then: !input motion_after

  - delay: !input cooldown

